using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraGrid.Views.Grid;

namespace DXApplication2
{
    public partial class frmKhachHang : XtraForm
    {
        private quanlycuahangEntities dbContext;

        public frmKhachHang()
        {
            InitializeComponent();
            this.loadGridData();
        }

        private void gridView1_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {
            dbContext.SaveChanges();
        }

        private void btnXoa_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            if (this.gridView1.GetFocusedRowCellValue("MaKH") == null)
            {
                this.khachhangsBindingSource.CancelEdit();
            } else
            {
                this.khachhangsBindingSource.RemoveCurrent();
                dbContext.SaveChanges();
            }
        }

        private void btnXoa2_Click(object sender, EventArgs e)
        {
            if (this.gridView1.GetFocusedRowCellValue("MaKH") == null)
            {
                this.khachhangsBindingSource.CancelEdit();
            }
            else
            {
                if (XtraMessageBox.Show(string.Format("Xóa khách hàng {0} ?", this.gridView1.GetFocusedRowCellValue("TenKH")),
                    "Xác nhận", MessageBoxButtons.YesNo) == DialogResult.Yes)
                {
                    this.khachhangsBindingSource.RemoveCurrent();
                    dbContext.SaveChanges();
                }
            }
        }

        private void btnThem_Click(object sender, EventArgs e)
        {
            this.gridView1.AddNewRow();
            this.gridView1.ShowEditForm();
        }

        private void btnSua_Click(object sender, EventArgs e)
        {
            this.gridView1.ShowEditForm();
        }
       
        private void loadGridData()
        {

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            if (dbContext == null)
            {
                dbContext = new quanlycuahangEntities();
            }
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.khachhangs.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                khachhangsBindingSource.DataSource = typeof(khachhang);
                khachhangsBindingSource.DataSource = dbContext.khachhangs.Local.ToBindingList();
            }, TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void btnTimKiem_Click(object sender, EventArgs e)
        {
            using (ctrlTimKiemKH myControl = new ctrlTimKiemKH())
            {
                if (XtraDialog.Show(myControl, "Tìm kiếm", MessageBoxButtons.OKCancel) == DialogResult.OK)
                {
                    String[] result = myControl.getResult();
                    gridView1.Columns[result[0]].FilterInfo =
                            new ColumnFilterInfo(result[0] +" LIKE '%" + result[1] + "%' ");
                }

            }
        }

        private void gridView1_ShownEditor(object sender, EventArgs e)
        {
            if (gridView1.FocusedColumn.FieldName.Equals("DiaChi"))//Don't work only for this column
            {
                TextEdit currentEditor = (sender as GridView).ActiveEditor as TextEdit;
                if (currentEditor != null)
                {
                    AutoCompleteStringCollection customSource = new AutoCompleteStringCollection();
                    customSource.Add("Quang Ngai");
                    customSource.Add("Quang Nam");
                    customSource.Add("Quang Binh");

                    currentEditor.MaskBox.AutoCompleteMode = AutoCompleteMode.SuggestAppend;
                    currentEditor.MaskBox.AutoCompleteSource = AutoCompleteSource.CustomSource;
                    currentEditor.MaskBox.AutoCompleteCustomSource = customSource;
                }
            }
        }

        private void gridView1_EditFormPrepared(object sender, EditFormPreparedEventArgs e)
        {
            foreach (Control control in e.Panel.Controls)
            {
                foreach (Control textEdit in control.Controls)
                {
                    if (!(textEdit is TextEdit)) continue;
                    if (textEdit.Name == "Update")
                    {
                        
                    }
                }
            }
        }
    }
}