using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraGrid.Views.Grid;

namespace DXApplication2
{
    public partial class frmSanPham : DevExpress.XtraEditors.XtraForm
    {
        quanlycuahangEntities dbContext;
        public frmSanPham()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            dbContext = new quanlycuahangEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.sanphams.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                sanphamsBindingSource.DataSource = dbContext.sanphams.Local.ToBindingList();
            }, TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void gridView1_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {
            dbContext.SaveChanges();
        }

        private void btnXoa_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            if (this.gridView1.GetFocusedRowCellValue("MaSP") == null)
            {
                this.sanphamsBindingSource.CancelEdit();
            }
            else
            {
                this.sanphamsBindingSource.RemoveCurrent();
                dbContext.SaveChanges();
            }
        }

        private void btnXoa2_Click(object sender, EventArgs e)
        {
            if (this.gridView1.GetFocusedRowCellValue("MaSP") == null)
            {
                this.sanphamsBindingSource.CancelEdit();
            }
            else
            {
                if (XtraMessageBox.Show(string.Format("Xóa sản phẩm {0} ?", this.gridView1.GetFocusedRowCellValue("TenSP")),
                    "Xác nhận", MessageBoxButtons.YesNo) == DialogResult.Yes)
                {
                    this.sanphamsBindingSource.RemoveCurrent();
                    dbContext.SaveChanges();
                }
            }
        }

        private void btnThem_Click(object sender, EventArgs e)
        {
            this.gridView1.AddNewRow();
            this.gridView1.ShowEditForm();
        }

        private void btnSua_Click(object sender, EventArgs e)
        {
            this.gridView1.ShowEditForm();
        }

        private void loadGridData()
        {

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            if (dbContext == null)
            {
                dbContext = new quanlycuahangEntities();
            }
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.khachhangs.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                sanphamsBindingSource.DataSource = typeof(khachhang);
                sanphamsBindingSource.DataSource = dbContext.khachhangs.Local.ToBindingList();
            }, TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void btnTimKiem_Click(object sender, EventArgs e)
        {
            using (ctrlTimKiemKH myControl = new ctrlTimKiemKH())
            {
                if (XtraDialog.Show(myControl, "Tìm kiếm", MessageBoxButtons.OKCancel) == DialogResult.OK)
                {
                    String[] result = myControl.getResult();
                    gridView1.Columns[result[0]].FilterInfo =
                            new ColumnFilterInfo(result[0] + " LIKE '%" + result[1] + "%' ");
                }

            }
        }
    }
}