//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public byte[] AnhSP { get; set; }
        public Nullable<decimal> GiaGoc { get; set; }
    }
}
